api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination:
            enabled: true
            items_per_page: 10
            client_items_per_page: true
            maximum_items_per_page: 100
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']